const notas = [
  {
    id: 1,
    titulo: "Tarea de Matemáticas",
    contenido: "Resolver problemas de álgebra y geometría",
    fecha: "2023-07-28",
    prioridad: "Alta",
    color: "#F4A6C8",
  },
  {
    id: 2,
    titulo: "Preparar Presentación",
    contenido: "Revisar diapositivas y ensayar discurso",
    fecha: "2023-07-29",
    prioridad: "Media",
    color: "#B2F7E2",
  },
  {
    id: 3,
    titulo: "Comprar víveres",
    contenido: "Leche, huevos, pan, frutas",
    fecha: "2023-07-28",
    prioridad: "Baja",
    color: "#E0B0FF",
  },
  {
    id: 4,
    titulo: "Cita con el médico",
    contenido: "Llevar los resultados de los exámenes",
    fecha: "2023-08-03",
    prioridad: "Alta",
    color: "#F4A6C8",
  },
  {
    id: 5,
    titulo: "Proyecto de Diseño",
    contenido: "Completar bocetos y preparar maquetas",
    fecha: "2023-07-31",
    prioridad: "Media",
    color: "#B2F7E2",
  },
  {
    id: 6,
    titulo: "Llamar a María",
    contenido: "Confirmar la reunión del próximo viernes",
    fecha: "2023-07-30",
    prioridad: "Baja",
    color: "#E0B0FF",
  },
  {
    id: 7,
    titulo: "Practicar guitarra",
    contenido: "Aprender nuevos acordes y melodías",
    fecha: "2023-07-29",
    prioridad: "Media",
    color: "#B2F7E2",
  },
  {
    id: 8,
    titulo: "Pagar factura del teléfono",
    contenido: "Revisar el monto y realizar el pago en línea",
    fecha: "2023-08-02",
    prioridad: "Alta",
    color: "#F4A6C8",
  },
  {
    id: 9,
    titulo: "Planificar vacaciones",
    contenido: "Investigar destinos y hacer reservaciones",
    fecha: "2023-08-05",
    prioridad: "Alta",
    color: "#F4A6C8",
  },
  {
    id: 10,
    titulo: "Leer libro recomendado",
    contenido: "Empezar con el primer capítulo",
    fecha: "2023-07-30",
    prioridad: "Baja",
    color: "#E0B0FF",
  },
];

export default notas;
